# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-11 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_action_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='action',
            name='content',
            field=models.TextField(default=b'content', max_length=20000, verbose_name=b'Details'),
        ),
        migrations.AlterField(
            model_name='action',
            name='title',
            field=models.CharField(default=b'title', max_length=1024, verbose_name='Title'),
        ),
    ]
