# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-11 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161211_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='content',
            field=models.TextField(max_length=20000, null=True, verbose_name=b'Details'),
        ),
        migrations.AlterField(
            model_name='action',
            name='title',
            field=models.CharField(max_length=1024, null=True, verbose_name='Title'),
        ),
    ]
