# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-15 03:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161211_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
